config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/home',     to: 'static_pages#home'
  get '/static_pages', to: 'static_pages#home'
  get '/management', to: 'static_pages#management'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  ##get '/group', to: 'groups#show'
  resources :users
  resources :groups
  resources :uploads
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :users, through: :group_memberships
    has_many :group_memberships
    has_many :uploads, through: :file_permissions
    
    validates(:name, presence:true, length: {maximum: 50})
    self.per_page = 10
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update, :destroy]
 
 
  def index
    if(current_user.admin?)
      @groups = Group.paginate(page: params[:page])
 
    else
      @groups = current_user.groups.paginate(page: params[:page])
    
    end
    
    respond_to do |f|
      f.js
    end
  end
  
  
  def show
    @group = Group.find(params[:id])
    @members = @group.users.paginate(page: params[:page])
    
    respond_to do |f|
      f.js
    end
  end
  
  def new
    @group = Group.new
    
    respond_to do |f|
      f.js
    end
  end
  
  def create
    @group = Group.new(group_params)
    if @group.save
       @group.group_memberships.create(user: current_user, owner: true, permission_share_files: true,permission_invite_users: true)
        
       flash[:success] = 'New group created'
       respond_to do |f|
        f.js 
       end
       
    else
      respond_to do |f|
        f.js {render 'new'}
      end
    end
  end
  
  def edit
    @group = Group.find(params[:id])
    
    
    
    respond_to do |f|
      f.js
    end
  end
  
  def update
    respond_to do |f|
      f.js
    end
    
    @group = Group.find(params[:id])
    if @group.update_attributes(group_params)
      flash[:success] = "group updated"
      redirect_to @group
    else
      render 'edit'
    end
  end
  
  def destroy
    Group.find(params[:id]).destroy
    flash[:success] = "Group deleted"
    
    respond_to do |f|
        f.js 
    end
    
  end
  
  private
      def group_params
        params.require(:group).permit(:name)
      end
      
      def logged_in_user
        unless logged_in?
          store_location
          flash[:danger] = "please log in"
          redirect_to login_url
        end
      end
      
      def correct_user
        u_id = group_owner_id
        @user = User.find(u_id)
        redirect_to(root_url) unless current_user?(@user)
      end
      
      def admin_user
        redirected_to(root_url) unless current_user.admin?
      end

      def group_owner_id
       @group = Group.find(params[:id])
       g_id = @group.id
       u_id_array = @group.group_memberships.where(owner: true).pluck(:user_id)
       u_id = u_id_array[0] 
       return u_id
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
    def group_owner(group)
        g_id = group.id
        u_id_array = group.group_memberships.where(owner: true).pluck(:user_id)
        u_id = u_id_array[0]
        u_name = User.find(u_id).name
        return u_name
    end   
    
    def group_owner_id(group)
       g_id = group.id
       u_id_array = group.group_memberships.where(owner: true).pluck(:user_id)
       u_id = u_id_array[0] 
       return u_id
    end
    
    def group_permissions(group)
        
    end
    
    def current_user_is_member?(group)
        group.users.pluck(:name)
    end
    
    def current_user_permission_check(group)
        
            g_mems = group.group_memberships
            u_id_arr = g_mems.where(owner: true).or(g_mems.where(permission_share_files: true)).pluck(:user_id)
            return u_id_arr.include?(current_user.id)
                
    end
end

app/views/groups/_group.html.erb
<tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
  <td><%= link_to group.name, group, remote: true %></td>
  <td><%= group_owner(group) %></td>
  <td><%= group.id %></td>
</tr> 

app/views/groups/_index.html.erb
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>My Groups  <%= link_to 'New Group', new_group_url, remote: true, class: "btn btn-primary" %></h3>
      
    </div>
    
    <table class="table table-condensed" style="border-collapse:collapse;">
      <thead>
        <tr>
	      <th>Group Name</th>
	      <th>Group Owner</th>
	      <th>Group ID</th>
        </tr>
      </thead>
      
      <tbody>


        <tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
        <%= render @groups %>
        </tr>
 
        <%= will_paginate @groups%>
        
	 
      </tbody>
    </table>
  </div>
  
  <div id="members-show">
    
  </div>

 
        
	     <div id="new-show">
	       
	     </div>  
	     
  
</div>

app/views/groups/_member.html.erb
<tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
  <td><%= link_to member.name, member, remote: true%></td>
  <td><%= member.email %></td>
  
</tr>

app/views/groups/_new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3>Create New Group</h3>
    </div>
   
	
    <div class="col-md-6 col-md-offset-3">
    <%= form_for(:group ,url: groups_path, remote: true) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.submit "Create group", class: "btn btn-primary" %>
    <% end %>
    </div>
    
</div>
	    
     

  
  
  

app/views/groups/_show.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
      <h3>Members - <%= @group.name %>  
      <%= link_to 'Edit Group', edit_group_url, remote: true, class: "btn btn-primary" %>
      <%= link_to 'Delete Group', @group, method: :delete, remote: true, class: "btn btn-primary" , data: {confirm: "Are you sure?"} %>
      
      
      </h3>
    </div>
    
    <table class="table table-condensed" style="border-collapse:collapse;">
      <thead>
        <tr>
	      <th>Name</th>
	      <th>Email</th>
        </tr>
      </thead>
      
      <tbody>

        <tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
        <%= render partial: "member", collection: @members%>
        </tr>
 
        <%= will_paginate @members%>
        
	 
      </tbody>
    </table>
  </div>

app/views/groups/create.js.erb
$.ajax({
      type: "GET",
      url: "<%= groups_url %>"
});

app/views/groups/destroy.js.erb
$.ajax({
      type: "GET",
      url: "<%= groups_url %>"
});

app/views/groups/index.js.erb
$("#replace-content").html("<%= j render partial: 'groups/index' %>");
$('.pagination a').attr('data-remote', 'true');

app/views/groups/new.js.erb
$("#new-show").html("<%= j render partial: 'groups/new' %>");

app/views/groups/show.js.erb
$("#members-show").html("<%= j render partial: 'groups/show' %>");