config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/home',     to: 'static_pages#home'
  get '/static_pages', to: 'static_pages#home'
  get '/management', to: 'static_pages#management'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  ##get '/group', to: 'groups#show'
  resources :users
  resources :groups
  resources :uploads
end

app/models/upload.rb
class Upload < ApplicationRecord
    belongs_to :user
    has_many :groups, through: :file_permissions 
    
    validates(:private, presence:true)
    
    has_attached_file :attachment
    
    validates_attachment_size :attachment, :in => 0..4000.kilobytes 
    
    validates_attachment_content_type :attachment, :content_type => ["application/msword", "application/pdf","text/plain","application/x-compressed","application/excel", /\Aimage\/.*\Z/]
    
    
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :logged_in_user
  
  def index
    respond_to do |f|
      f.js
    end
  end
  
  
  def index
    if(current_user.admin?)
      @uploads = Upload.paginate(page: params[:page])
    
    
    else
      @uploads = Upload.where(private: false)
      
      @uploads = @uploads.join(current_user.uploads)
      
      current_user.groups.each do |group|
       @uploads = @uploads.joins(group.uploads)
       
       
      end
      
      @uploads = @uploads.paginate(page: params[:page])
      
      respond_to do |f|
        f.js
      end
    end
  
  end 

  
  def show
    @upload = Upload.find(params[:id])
    send_file(Paperclip.io_adapters.for(@upload.attachment).path, :type => @upload.attachment_content_type, :disposition => "attachment", :filename => @upload.attachment_file_name)
    render js: "window.location = '#{uploads_path}'"
  end
  
  def new
    @upload = Upload.new
    respond_to do |f|
      f.js
    end
  end 
      
  def create
    @upload = Upload.new(upload_params.merge(user_id: current_user.id))
    if @upload.save
      respond_to do |f|
      f.js
    end
    else
      render action: 'new'
    end
  end
  
  def edit
  
  end

  def update
  
  def destroy

  end

end
    private

    def upload_params
      params.require(:upload).permit(:attachment, :private)
    end
    
    
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/uploads/_index.html.erb
<div class="col-lg-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3>Files  <%= link_to 'Upload New File', new_upload_url, remote: true, class: "btn btn-primary" %></h3>
      
    </div>
    
    <table class="table table-condensed" style="border-collapse:collapse;">
      <thead>
        <tr>
	      <th>File Name</th>
	      <th>File Uploader</th>
	      
        </tr>
      </thead>
      
      <tbody>


        <tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
        <%= render @uploads %>
        </tr>
 
        <%= will_paginate @uploads%>
        
	 
      </tbody>
    </table>
  </div>
  
  <div id="">
    
  </div>

 
        
	     <div id="new-upload">
	       
	     </div>  
	     
  
</div>

app/views/uploads/_new.html.erb
<%= form_for(@upload, multipart: true, remote: true) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :File%>
    <%= f.file_field :attachment %>
    <!--<input class='form-control' name='upload[private]' id='upload_private' type='text_field' value=false>-->
  </div>
  
  <div class="field">
    
    <%= f.hidden_field :private, class: 'hidden-f', value: false%>
  </div>
  
  <div class="actions">
    <%= f.submit 'Upload', class: "btn btn-primary" %>
    <%= link_to 'Cancel', uploads_path, class: "btn btn-primary", remote: true%>
  </div>
  
  <h2>Share with: <button id= "add-share" class="btn btn-success btn-add" type="button" style=display:none;><span class="glyphicon glyphicon-plus"></span></button></h2>
  
  <select class="form-control input-lg" id="upload-settings" style="margin-left:10px;">
	    <option value=1>Public</option>
	    <option value=2>Private</option>
	    <option value=3>Groups</option>
	    
  </select>
  
  <div id="add-select">
  
  </select>
  </div>
<% end %>

app/views/uploads/_upload.html.erb
<tr data-toggle="collapse" data-target="#demo1" class="accordion-toggle">
  <td><%= link_to upload.attachment_file_name, upload %></td>
  <td><%= upload.user.name %></td>
  
</tr> 

app/views/uploads/create.js.erb
alert('success!');

$.ajax({
      type: "GET",
      url: "<%= uploads_url %>"
});

app/views/uploads/index.js.erb
$("#replace-content").html("<%= j render partial: 'uploads/index' %>");

app/views/uploads/new.js.erb
$("#new-upload").html("<%= j render partial: 'uploads/new' %>");


$(document).ready(function(){

  <!--$("#upload-settings").trigger('change');-->


  $("#upload-settings").change(function(){
  
      if($(this).val() == "1"){
        priv_val = false;
      } else{
        priv_val = true;
      }
      
      $("#upload_private").attr("value",priv_val);
      
      if ($(this).val() == "3"){
      
          <% current_user.groups.each do |group| %>
          
              <% if current_user_permission_check(group) %>
                  $("#add-select").append("<select class='form-control input-lg groupselect' id = 'initial-gs' style='margin-left:10px;display:none;'><option value='none'>Select Group</option></option><option value=<%= group.id %>><%= group.name %></option></select>");
                  
              <% end %>
              
          <% end %>
      
          $( "#add-select" ).show();
          $( ".groupselect").show();
          $( "#add-share" ).show();
          
       } 
       
       else {
          $("#add-share").hide();
          $("#add-select").empty();
       }
       
        $(".groupselect").change(function(){
      var selectValue=[];
      $(".groupselect").each(function(){
          selectValue.push(this.value);
      });
  
      $(this).siblings(".groupselect").find("option").removeAttr("disabled").filter(function(){
         var a=$(this).parent("select").val();
         return (($.inArray(this.value, selectValue) > -1) && (this.value!=a))
      }).attr("disabled","disabled");
  });
  
  });
  
 
 
 $( "#add-share" ).click(function() {
    $( "#initial-gs" ).clone().removeAttr('id').appendTo( "#add-select");
    
    $( ".groupselect").show();
    
    $(".groupselect").change(function(){
      var selectValue=[];
      $(".groupselect").each(function(){
          selectValue.push(this.value);
      });
  
      $(this).siblings(".groupselect").find("option").removeAttr("disabled").filter(function(){
         var a=$(this).parent("select").val();
         return (($.inArray(this.value, selectValue) > -1) && (this.value!=a))
      }).attr("disabled","disabled");
  });
  });


  
  
  


});