config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/home',     to: 'static_pages#home'
  get '/static_pages', to: 'static_pages#home'
  get '/management', to: 'static_pages#management'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  ##get '/group', to: 'groups#show'
  resources :users
  resources :groups
  resources :uploads
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="empty">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header black-bg">
        <div class="sidebar-toggle-box">
          <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        
        <%= link_to "fileshareapp", root_path, class: "logo" %>
        
        <div class="nav notify-row" id="top_menu">
          
          <ul class="nav top-menu">
            
            <li class="dropdown">
            </li>
            
           
          </ul>
          
        </div>
        <div class="top-menu">
          <ul class="nav pull-right top-menu">
            <% if logged_in? %>
              <li><%= link_to "Log out", logout_path, method: :delete, class: "logout" %></li>
            <% else %>
              <li><%= link_to "Log in", login_path, class: "logout", remote: true %></li>
            <% end %>
          </ul>
        </div>
</header>

app/views/layouts/_rightbar.html.erb
  <h3>Personal Notes</h3>
  
 
  <div class="desc">
    <div class="thumb">
      <span class="badge bg-theme"><i class="fa fa-clock-o"></i></span>
    </div>
    <div class="details">
      <p><muted>18 Hours Ago</muted><br/>
        <a href="#">Daniel Pratt</a> purchased a wallet in your store.<br/>
      </p>
    </div>
  </div>

  
  <h3>Shared People</h3>
  
  <div class="desc">
    <div class="thumb">
      
    </div>
    <div class="details">
      <p><a href="#">DAN ROGERS</a><br/>
        <muted>Available</muted>
      </p>
    </div>
  </div>
 
  <div class="desc">
    <div class="thumb">
      
    </div>
    <div class="details">
      <p><a href="#">Zac Sniders</a><br/>
        <muted>Available</muted>
      </p>
    </div>
  </div>
  
  <div class="desc">
    <div class="thumb">
      
    </div>
    <div class="details">
      <p><a href="#">Marcel Newman</a><br/>
        <muted>Available</muted>
      </p>
    </div>
  </div>
  

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_sidebar.html.erb
<aside>
        <div id="sidebar"  class="nav-collapse ">
         
          <ul class="sidebar-menu" id="nav-accordion">
            
            <p class="centered"><a href="profile.html"></a></p>
            <h5 class="centered">Navigation Menu</h5>            
            
            <% if logged_in? && current_user.admin?%>
            <li class="mt">
                <i class="fa fa-dashboard"></i>
                <%= link_to "Admin Dashboard", 'management', remote: true %>
            </li>
            <% end %>
            
            <li class="sub-menu">
              
                <i class="fa fa-book"></i>
                <%= link_to "Files", 'uploads', remote: true %>
              
            </li>
            <li class="sub-menu">
              
                <i class="fa fa-book"></i>
                <%= link_to "Groups", 'groups', remote: true %>
              
            </li>
            <li class="sub-menu">
              
                <i class="fa fa-book"></i>
                <%= link_to "Users", 'users', remote: true %>
              
            </li>
            <li class="sub-menu">
              
                <i class="fa fa-book"></i>
                <%= link_to "Create new user", 'users/new', remote: true %>
              
            </li>
          </ul>
          
        </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <section id="container" >
      <%= render 'layouts/header' %>
      <%= render 'layouts/sidebar' %>
    
      <section id="main-content">
        <section class="wrapper">
          <div class="row">
            <%= yield %>
            <div class="col-lg-3 ds">
              <%= render 'layouts/rightbar' %>
            </div>
          </div>
        </section>
      </section>
    
      <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= render 'layouts/footer' %>
      
   </section>
   
  </body>
</html>